---
# file: roles/logstash/handlers/main.yml

- name: enable logstash service
  systemd:
    daemon_reload: yes
    name: logstash
    enabled: yes
    masked: no

- name: start logstash service
  systemd:
    name: logstash
    state: started

- name: restart logstash service
  systemd:
    name: logstash
    state: restarted
