---
# file: roles/filebeat/handlers/main.yml

- name: enable filebeat service
  systemd:
    daemon_reload: yes
    name: filebeat
    enabled: yes
    masked: no

- name: restart filebeat service
  systemd:
    name: filebeat
    state: restarted
