---
# file: roles/prometheus/tasks/main.yml

- name: extract prometheus tar.gz
  unarchive:
    src: "{{ prometheus_ver }}.tar.gz"
    dest: /opt/
    owner: root
    group: root

- name: copy prometheus.yml
  template:
    src: prometheus.yml
    dest: "{{ prometheus_data }}/prometheus.yml"
    owner: root
    group: root
    mode: 0644
    backup: yes
  notify:
    - restart prometheus service

- name: copy systemd prometheus.service
  template:
    src: prometheus.service.j2
    dest: /lib/systemd/system/prometheus.service
    owner: root
    group: root
    mode: 0644
    backup: no
  notify:
    - enable prometheus service
    - restart prometheus service
