---
# file: roles/grafana/handlers/main.yml

- name: enable grafana-server service
  systemd:
    daemon_reload: yes
    name: grafana-server
    enabled: yes
    masked: no

- name: start grafana-server service
  systemd:
    name: grafana-server
    state: started

- name: restart grafana-server service
  systemd:
    name: grafana-server
    state: restarted
